### ISSUE TITLE
In fullscreen mode, --scale-down prevents image from centering

### ISSUE THREAD

**Issue by pharada** [derf/feh#192] opened 2015-05-23 00:03 UTC
Starting in version 2.13, images do not center in fullscreen mode when --scale-down is passed. If --scale-down is NOT passed, images center correctly in fullscreen mode. This applies to all images regardless of size. According to the manpage, --scale-down is supposed to have no effect in fullscreen mode; fullscreen mode always scales down. I use the Awesome tiling window manager.

Version 2.12.1 had (IMO) the correct behavior, where images would center correctly regardless of whether --scale-down was passed.

The following change from commit 4fb72f163060cf7d9663b64e535401f47e395151 appears to have introduced the problem:

    diff --git a/src/winwidget.c b/src/winwidget.c
    index 01bb454..a1b78d3 100644
    --- a/src/winwidget.c
    +++ b/src/winwidget.c
    @@ -433,7 +443,8 @@ void winwidget_render_image(winwidget winwid, int resize, int force_alias)
            feh_calc_needed_zoom(&(winwid->zoom), winwid->im_w, winwid->im_h, winwid->w, winwid->h);

    -	if (resize && (winwid->full_screen || (opt.geom_flags & (WidthValue | HeightValue)))) {
    +	if (resize && !opt.scale_down && (winwid->full_screen
    +                     || (opt.geom_flags & (WidthValue | HeightValue)))) {
            int smaller;	/* Is the image smaller than screen? */
            int max_w = 0, max_h = 0;
     
Reverting that hunk fixes the issue, but I haven't tested whether it breaks anything else.

**Comment by derf** [comment] 2015-05-23 07:29
Yup, this is a bug introduced by a patch to make --scale-down and --geometry work together. I'm looking into it.

**Comment by derf** [comment] 2015-05-23 07:34
could you verify that the issue is fixed in git HEAD for you?

**Closed** 2015-05-23 07:33 UTC
Labels: bug

**Comment by pharada** [comment] 2015-05-24 01:53
Yep, looks like that fixes it. Thanks!
