### ISSUE TITLE
run an action on an arbitrary file?

### ISSUE THREAD

**Issue by atomGit** [derf/feh#508] opened 2020-02-12 06:35 UTC
i am loving feh - it fits very well with my project

after searching and reading the man page i'm still not sure whether i can create an action to do what needs done

i want to create an action that will delete the image as well as perform a command (mv) on an arbitrary file ... can do?

longer version...
i'm using feh to view spectrograph images (created by ffmpeg) of mp3 files - if the spectrograph looks like crap, i want to dump the png image and move the mp3 to another folder

**Comment by Ferada** [comment] 2020-02-14 11:11
Guessing to how your setup is:

```sh
$ ls
foo.png foo.mp3 bar.png bar.mp3
```

As far as I know you'll have to do a bit of processing for the filename replacement, but then it's really not much of a problem to do something like this:

```sh
feh -A 'base=$(basename %F .jpg); echo mv $base.mp3 output/$base.mp3 && echo rm %F'
```

There's likely a hundred other ways, but this gives you an idea of how to do this.

I'd recommend thoroughly testing this and only then removing the `echo`!

**Comment by atomGit** [comment] 2020-02-14 14:04
thanks - this is great!

should anyone else come across this, i found what may be a "better" method of stripping the path from a string containing a file name without having to run basename...

`"${sFile##*/}"`

i've very new to bash scripting, but that works great for me

**Comment by atomGit** [comment] 2020-02-14 16:11
running into a little problem here...

```
mp3working/
    input/my.mp3
    junk/
    spectrograph/my.png
    mp3script.sh
```

when i run in mp3script.sh ...

`sFileIn=my.mp3`

`feh -F -d -Z -A 'mv "input/${sFileIn}" junk && echo rm "spectrograph/${sFileIn%.*}.png"' "spectrograph/${sFileIn%.*}.png"`

... the entire 'input' folder is moved to 'junk' and feh says ...

`feh WARNING: Unrecognized format specifier %.`

so it looks like there may be some word splitting going on here regarding the 'input' folder problem and some extra processing or something regarding %?

the latter i can fix by feeding feh a normal variable ( '$sFile'  ) but i'm curious why the error occurs ( `${sFileIn%.*}.png` works fine outside of feh )

also i'm not entirely sure what to do if the 'junk' folder had spaces in the name

**Comment by Ferada** [comment] 2020-02-14 16:20
> `feh WARNING: Unrecognized format specifier %.`

Look at `man feh` and the section "FORMAT SPECIFIERS" - in short, insert `%%` for a literal "%" in the shell command.

> also i'm not entirely sure what to do if the 'junk' folder had spaces in the name

As usual, quote the folder name.

**Comment by atomGit** [comment] 2020-02-14 19:11
feh seems to be doing something to commands in an action that bash doesn't - in a shell script this works...

`mv "input/${sFile}" 'junk'`

however when that's added as an action, the entire /input/ folder is moved to the junk folder and i don't know why...

`feh -F -d -Z -A 'mv "input/${sFile}" junk && rm "spectrograph/${sFile%%.*}.png"' "spectrograph/${sFile%.*}.png"`

**Comment by Ferada** [comment] 2020-02-16 11:32
> `feh -F -d -Z -A 'mv "input/${sFile}" junk && rm "spectrograph/${sFile%%.*}.png"' "spectrograph/${sFile%.*}.png"`

You're doing it a bit differently now than initially suggested since `sFile` is passed in into the argument definition (or, well it **should** be). It might simply be easier to use `feh`'s format specifier `%F` to get the currently displayed file name.

So, what's happening here? `sFile` is defined in your current shell instance (like the one from the script). Then `feh` gets invoked. Due to the single quote the command line remains unexpanded, so `feh` really gets `mv "input/${sFile}" junk && rm "spectrograph/${sFile%%.*}.png"` as the command definition. When the action is then invoked, `sFile` **isn't** defined, since it probably wasn't exported with `export sFile`. Therefore, the command that eventually gets executed is `mv "input/" junk && rm "spectrograph/.png"`, which is what you've seen.

**Comment by atomGit** [comment] 2020-02-16 12:13
in the example you provided, `mv $base.mp3 output/$base.mp3` is also in single quotes, so how would `$base.mp3` get expanded?

**Comment by atomGit** [comment] 2020-02-16 13:27
this works, until 'echo' is removed...
`feh -A "echo mv ""input/${sFile}"" "'junk'" && echo rm %F" "spectrograph/${sFile%.*}.png"`
so does this...
`feh -A "echo mv input/${sFile} 'junk' && echo rm %F" "spectrograph/${sFile%.*}.png"`

remove the first 'echo' and...
`mv: cannot stat 'input/01.': No such file or directory`
`mv: cannot stat 'Encounters.mp3': No such file or directory`

**Comment by Ferada** [comment] 2020-02-16 13:32
> in the example you provided, `mv $base.mp3 output/$base.mp3` is also in single quotes, so how would `$base.mp3` get expanded?

Correct, it doesn't get expanded immediately, instead it will be expanded by the shell that `feh` invokes when it executes the command.

That is, the shell command would've been `base=$(basename foo.png .png); echo mv $base.mp3 output/$base.mp3 && echo rm foo.png`. That's simply a shell command sequence and all executed in the same shell, so the variable then has a value defined.

**Comment by atomGit** [comment] 2020-02-16 13:37
so then your original example also wouldn't work?

how does that help me?

if there's a better way to do this, i'm all ears, but i need to get this done

**Comment by derf** [comment] 2020-04-11 07:19
I hope you managed to resolve your issue. Closing this thread, as it is a shell scripting discussion and not a bug in feh itself.

**Closed by derf** 2020-04-11 07:19 UTC
