### ISSUE TITLE
Unloadable image detection is slow with Imlib2 ≥ 1.6

### ISSUE THREAD

**Issue by zotho** [derf/feh#505] opened 2020-01-28 21:04 UTC
When I run `feh Folder_name` and iterate over the images, feh is stuck on large .mp4 files. It logs:
```
feh WARNING: *.mp4 - No Imlib2 loader for that file format
...
```
And feh may just not respond to any commands.
Is it possible to add command line arguments:
- list of extensions that can be opened
- list of extensions that can't be opened
- file size limit

All optional

**Comment by derf** [comment] 2020-03-29 06:06
It's possible, but I'd rather not re-implement functionality already provided by other tools. Do you see a case where a variation on `feh $(find Folder_name -not -name '*.mp4')` wouldn't work?

**Comment by zotho** [comment] 2020-03-29 06:16
I think with `find` this will work fine

**Comment by derf** [comment] 2020-03-29 08:32
Glad to hear. Closing this issue as wontfix for now.

**Comment by mallniya** [comment] 2020-05-07 20:36
Hello, it seems that I'm not the only one bothered by this issue (https://github.com/derf/feh/issues/520 another example).
Generic unix tools work (as they always do), but this is quite cumbersome to print, especially if one has many other formats in target directory. It's finite list of formats feh supports, so why just don't try to load files with unsupported format or at least has an option to?
Also there are 2 cases where unix tools are inapplicable: opening directory from UI and setting white-/blacklist through themes.
@derf, please reconsider this feature in one form or another.

**Comment by kpcee** [comment] 2020-05-08 11:46
Nice to see that others also have problems with this behavior of feh. The workaround mentioned here is unfortunately absolutely useless for me. As soon as the path or filename contains spaces, the output of find doesn't work with feh or does anyone know how to put the output of find in quotes so that feh loads the paths correctly?

**Comment by Ferada** [comment] 2020-05-11 09:13
> Nice to see that others also have problems with this behavior of feh. The workaround mentioned here is unfortunately absolutely useless for me. As soon as the path or filename contains spaces, the output of find doesn't work with feh or does anyone know how to put the output of find in quotes so that feh loads the paths correctly?

Not arguing either way, but `find . -print0 | xargs -0 feh` will deal all paths.

**Comment by kpcee** [comment] 2020-05-11 11:22
Thank you very much for this solution, it works for me too. I had spent over 2 hours on the internet to find a working solution the last days and didn't find one, but was close to it, only the -0 at xargs was missing.

I would suggest to extend the manual to include the info, so that others don't have to search for an own solution. Anyway, I am satisfied with it.

`find . -type f -iregex ".*\.\(jpg\|jpeg|bmp|png|pnm|tiff|gif\)$" -size -30M -print0 | xargs -0 feh`

This catch only supported formats and files smaller than 30 MB.

**Comment by kpcee** [comment] 2020-05-11 13:28
One disadvantage of this method I noticed now. the processing of the paths is done in chunks. If the paths are long enough and there are enough images, only a part of all paths is passed to feh. If you end feh with q, feh starts immediately again with the next chunk until all chunks are passed to feh. You can see this behaviour already with less than 1000 images, if the paths are long enough.

**Comment by derf** [comment] 2020-05-29 21:43
Apparently, Imlib2 1.6 (released in nov 2019) introduced major changes in its image loader. It has been reported on IRC that feh takes much longer to dismiss unloadable files as unloadable with Imlib 2 1.6 compared to 1.5.

So my previous assumption (feh doesn't get stuck on unloadable files for long when not using `--magick-timeout`) was wrong. I can reproduce the issue now.

**Comment by derf** [comment] 2020-05-31 07:19
Judging from the [Upstream Issue](https://phab.enlightenment.org/T8739), it might be an Imlib2 regression and unrelated to feh. Let's see how it turns out and whether feh needs a workaround in the meantime.

**Comment by 6gk** [comment] 2020-11-30 02:03
I have this issue and feh is borderline unusable when opening a dir that has mp4 files and cycling through them.

imlib2 v1.6.1, feh v3.3, ubuntu

In the meantime I'll hunt down and install an older imlib2 version, but it would be nice for it to be fixed, even if this isn't exactly your problem.

**Comment by derf** [comment] 2020-11-30 18:10
You're right, I forgot about this issue. Thank you for reminding me!

It doesn't look like Imlib2 is making progress, so I'm making feh check whehter a file looks like an image before attempting to load it via Imlib2. The check is based on magic bytes, so it should be fairly reliable. It will be possible to override it using an environment variable.

**Comment by 6gk** [comment] 2020-11-30 18:15
> It doesn't look like Imlib2 is making progress

That's honestly a serious bummer - for people who want an older version, i got mine [from debian's website](https://packages.debian.org/buster/amd64/libimlib2/download) ([missing dep here](https://packages.debian.org/buster/amd64/libjpeg62-turbo/download)), and it makes it so much more responsive.

> Thank you for reminding me!

And thank you for making such a nice project.

**Closed** 2020-11-30 18:27 UTC
Labels: Imlib2, bug

**Comment by lmoellendorf** [comment] 2024-11-24 09:25
I am using feh v3.10.3 and I am still seeing the same issue reported here. Is it a regression?
I using feh in a webdav mounted directory over a slow internet connection. As soon as feh enccounters an *.mp4 file it becomes unresponsive. 

I will try the [workaround using find and xargs](https://github.com/derf/feh/issues/505#issuecomment-626642236) and hope I am not affected by the [disadvantage](https://github.com/derf/feh/issues/505#issuecomment-626701909).
