### ISSUE TITLE
error reading GIF from stdin

### ISSUE THREAD

**Issue by bittorf** [derf/feh#621] opened 2021-07-24 14:21 UTC
when piping GIF files into feh, it aborts with:

```
$ cat file.gif | feh -
feh WARNING: /tmp/feh_stdin_KOla7l - No Imlib2 loader for that file format
```

This seems to happens with every GIF file. Other formats are working.
Tested with master 66fb4bc4a8f449d8065730a02049c0283c618e02

**Comment by derf** [comment] 2021-07-24 19:52
I can confirm that this is an issue for all GIF files. It appears to be caused by Imlib2 (feh's backend for loading images) refusing to load gif files that do not end in ".gif". You'll have the same problem if you rename a gif image to a different extension (or no extension at all) and try to open that one with feh.

In theory, Imlib2 should be able to handle all supported formats both with and without correct filenames. I'm still looking into why this isn't the case GIFs.

**Comment by derf** [comment] 2021-09-11 19:54
It is indeed an Imlib2 bug. I'm currently waiting for feedback on a patch.

In case you want to build your own patched Imlib2 version, the required change is quite simple:

```
diff --git a/src/modules/loaders/loader_gif.c b/src/modules/loaders/loader_gif.c
index cc8baa7..fbac9cc 100644
--- a/src/modules/loaders/loader_gif.c
+++ b/src/modules/loaders/loader_gif.c
@@ -18,6 +18,7 @@ load2(ImlibImage * im, int load_data)
    DATA32              colormap[256];
 
    fd = dup(fileno(im->fp));
+   lseek(fd, 0, SEEK_SET);
 
 #if GIFLIB_MAJOR >= 5
    gif = DGifOpenFileHandle(fd, NULL);
```

**Comment by derf** [comment] 2021-09-14 21:14
The issue has been fixed in Imlib2: https://git.enlightenment.org/legacy/imlib2.git/commit/?id=43f82f3bc80324282ec22cb6b7c0e0b3ca2b663f

**Comment by bittorf** [comment] 2021-09-19 14:58
I see the fix in Imlib2, but it does not seems to work?!

```
$ git clone https://git.enlightenment.org/legacy/imlib2.git
$ cd imlib2 && ./autogen.sh && ./configure && make && sudo make install && cd ..
$ git clone https://github.com/derf/feh.git
$ cd feh && make
$ cat /home/bastian/opencv-4.2.0/doc/images/camshift_face.gif | src/feh -
feh WARNING: /tmp/feh_stdin_v2fu0u - No Imlib2 loader for that file format
feh: No loadable images specified.
```
maybe I have to explicit enforce LDFLAGS?

**Comment by derf** [comment] 2021-09-25 12:15
Looks like. I think the trick is `rm -f /etc/ld.so.cache; ldconfig`, at least that worked when testing it in a Debian Bullseye Docker image.

**Closed** 2021-09-25 12:15 UTC
Labels: bug, Imlib2
