### ISSUE TITLE
Naive usage of feh *.jpg leads to core dump

### ISSUE THREAD

**Issue by heckruler** [derf/feh#335] opened 2017-10-01 16:46 UTC
Didn't read the manual and ran `feh *.jpg'    

Core dump. 

[core.zip](https://github.com/derf/feh/files/1347330/core.zip)

The right way to do that is feh -r or pass in a folder, but a core dump is a bug.  At a guess, sanitize thine inputs?

**Comment by derf** [comment] 2017-10-01 18:22
`feh *.jpg` is a valid command and should not lead to a core dump. However, I can't reproduce that behaviour here.

Which version of feh are you using? do you have any unusual files in your working directory?

**Comment by heckruler** [comment] 2017-10-02 16:04
feh version 2.14
Compile-time switches: curl exif xinerama

apport says 2.14-1
SIGSEGV in __libc_start_main()

There's probably a lot of unusual files, it's a dumping ground for random internet pics and  .xcfs. I was using feh to find which ones were unreadable. The core dump has the list of file names.   feh -u doesn't list any of the jpegs though.

what the....   oh wow. get this:

ls *.gif works as normal.  ls *.jpg complains ls: invalid option -- '0'    Which, yes, also gets reported by feh *.jpg.      And that's because there's a file name starting with a dash.   -0FO1qTblahblah.jpg.    Bash expands the * and command line thinks it's an argument. 

feh -0FO1qT-CUnG8J_iz_vrmPlIswo_VCK8WHcW_xcUogY.jpg   crashes.     I rename it and ls and feh work with *.jpg again.   I can name other files with a preceding -0 and feh works (oh, it still complains about the invalid option -- '0', but it chugs along and displays), ls just quits with the bad option. 

Here's the weirdo:
![-0fo1qt-cung8j_iz_vrmpliswo_vck8whcw_xcuogy](https://user-images.githubusercontent.com/12578174/31087029-c4c6531a-a758-11e7-9512-dc080aa96dc2.jpg)

Sorry, I could have dug deeper into this one before submitting a ticket.

**Comment by derf** [comment] 2017-10-02 16:57
Yeah, the issue is `-O`. It tells feh to output to a file instead of X11 and is meant to be used in thumbnail/index mode. Due to a missing option check, using it without thumbnail mode caused the segfault you observed.

It's fixed now, thanks for reporting it!

**Closed** 2017-10-02 16:57 UTC
Labels: bug, can't reproduce

**Comment by derf** [comment] 2017-10-02 16:58
(however, feh will still complain when you use `*` and have file names starting with `-`. use `feh -- *.jpg` to tell it that it shouldn't parse any of the file names as options, no matter how weird they may look)
