### ISSUE TITLE
--scale-down does not scale properly, crashes after a while

### ISSUE THREAD

**Issue by mklinik** [derf/feh#94] opened 2012-07-22 10:39 UTC
The image does not always fill the whole window. Sometimes, the image isn't displayed at all, and the window is just black.

I'm using version 2.5-10-ga62c48c on debian testing with xmonad.

How to reproduce:

1. Run feh with --scale-down and an image larger than the screen
        
        $ feh -. <some-jpeg>

2. Toggle window layouts several times

Result: The displayed image does not always fill the window. Sometimes, the image is displayed correctly. Sometimes the window is completely black. Sometimes the image is displayed tiny in the upper left corner of the window. After some layout switches, sometimes 10, sometimes 100, feh crashes with the following error message:

    X Error of failed request:  BadAlloc (insufficient resources for operation)
      Major opcode of failed request:  53 (X_CreatePixmap)
      Serial number of failed request:  273
      Current serial number in output stream:  277

**Comment by derf** [comment] 2015-11-15 11:41
Still not able to reproduce, but it should be fixed by dfe3c40f80f77a800479c31a51b1f3b1f648b0ea

**Closed by derf** 2015-11-15 11:41 UTC
Labels: bug
