### ISSUE TITLE
feh in daemonized mode crashes in feh_event_handle_stdin()

### ISSUE THREAD

**Issue by pvanstam** [derf/feh#631] opened 2021-09-18 18:14 UTC
I'm using feh in a daemonized python script, calling feh with subprocess.run().
feh 2.3 has no problems (up to 2.19). Since version 2.20 feh crashes.

Error with 3.7 is:
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 74 requests (74 known processed) with 0 events remaining.

or
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
feh: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

Issue can be resolved to remove the call to the function feh_event_handle_stdin() in main.c and recompiling.
code lines are:
	else if ((count > 0) && (FD_ISSET(0, &fdset)))
		feh_event_handle_stdin();

Issue seems clear. Since feh is started from a daemonized process there is no controlling terminal. Requesting input doesn't make sense an is troublesome. The call in main.c needs to have a check for a controlling terminal. Not sure how to do this, but can sort this out.
Will be followed up

Comments are welcome

**Comment by pvanstam** [comment] 2021-09-19 19:16
Added a fix in main.c. Made a pull request fot the fix. #632

**Comment by derf** [comment] 2021-09-19 19:18
Could you give me the subprocess.run invocation you're using? Does it happen when calling the Python script from a terminal or do I need to run it e.g. via systemd?

I think there's a slightly more elegant fix than #632, and I see where feh goes wrong, but I can't reproduce the issue yet and so I can't test methods of resolving it.

Also, thanks for reporting it and suggesting a bugfix!

**Comment by pvanstam** [comment] 2021-09-20 12:50
Send a test script directly. 
I'm using python3-daemon (2.1.2) for daemonizing (running in background) of an application.
With subprocess.run() starting feh for showing pictures in a Xorg environment.

Basically the script does:

import daemon, subprocess

def main():
     subprocess.run(["feh", "image.jpg"])

fileout = open("/var/log/fehtest.log", "w")
with daemon.DaemonContext(stderr=fileout, stdout=fileout):
    main()

**Comment by derf** [comment] 2021-09-21 19:49
Thanks a lot; now I understand what's going wrong. With this way of running feh, stdin is not connected at all, so the X11 connection uses file descriptor 0. feh mistakenly assumes that file descriptor 0 is always connected to stdin and therefore tries to read from it, even though it's X11 events and not terminal input in this case.

I have patched it as suggested by your pull request, though in a slightly more efficient manner.

**Closed** 2021-09-21 19:50 UTC
