### ISSUE TITLE
No handling of memory allocation of invalid size when calling init_imlib_fonts()

### ISSUE THREAD

**Issue by Hee-won** [derf/feh#712] opened 2023-06-12 08:00 UTC
Hi there.

There is no proper handling of the allocation of a buffer with an invalid size.

The invalid memory allocation happens in the function init_imlib_fonts() when called in the function main().

(The function is hidden as ?? in our report but is called in main.c:59)

Here is the output of the gdb results.

### Bug Report

(gdb) r
Starting program: /home/ubuntu/targets/feh-3.10/src/feh -l /home/ubuntu/pfuzz/feh/crashes/0xcc765e53_0xb1c1261c
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
malloc(): invalid size (unsorted)

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a21859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a8c26e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7bb6298 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7a942fc in malloc_printerr (str=str@entry=0x7ffff7bb8a50 "malloc(): invalid size (unsorted)") at malloc.c:5347
#4  0x00007ffff7a970b4 in _int_malloc (av=av@entry=0x7ffff7bebb80 <main_arena>, bytes=bytes@entry=27) at malloc.c:3736
#5  0x00007ffff7a99154 in __GI___libc_malloc (bytes=27) at malloc.c:3058
#6  0x00007ffff7a9e38f in __GI___strdup (s=0x555555579462 "/usr/local/share/feh/fonts") at strdup.c:42
#7  0x00007ffff7c10f9a in ?? () from /lib/x86_64-linux-gnu/libImlib2.so.1
#8  0x000055555555c1d5 in main (argc=3, argv=0x7fffffffe538) at main.c:59

### Envionment
OS: Ubuntu 20.04.5 LTS / 22.04 LTS
Release: Feh 3.10
Library: imlib2 1.6.1 and imlib2 1.7.4
Program: feh

### How to reproduce
$ feh -l poc-file
poc-file is attached.
[poc-file.txt](https://github.com/derf/feh/files/11719805/poc-file.txt)

**Comment by derf** [comment] 2023-06-21 16:25
Hi, thanks for the report!

This is an Imlib2 issue and cannot be fixed by feh. I also cannot reproduce it with a more recent Imlib2 version (1.10.0), so I'll assume that the bug no longer exists.

Let me know if you can reproduce it with that Imlib2 version or if there is something that I'm missing and that needs to be addressed in feh. I'll reopen the issue in that case.

**Closed by derf** 2023-06-21 16:25 UTC
Labels: Imlib2
